feign:
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 5000
        loggerLevel: basic

eureka:
  client:
    enabled: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

zuul:
  ignoredServices: '*'
  ignoredPatterns: /**/admin**
  prefix: /zuul-test-prefix
  routes:
    beer-catalog-service:
      path: /service/**
      service-id: beer-catalog-service
      sensitiveHeaders:

